### ISSUE TITLE
Can't create admin user

### ISSUE THREAD

**Issue by poblabs** [thomiceli/opengist#1]
Hey there, I am using this in a single user mode, and I typically create my single user account names as "admin". This won't let me create admin. Is that because it already exists? If so, I didn't see the password in the readme?

Thanks!

**Comment by thomiceli** [comment]
Hi, its because it would create a conflict between two URLs with the same path `/admin` (the one which show all gists for a user `/:user` and the hardcoded one which is the admin panel `/admin`).

https://github.com/thomiceli/opengist/blob/864880b4421efe93930ef986780ba9679507ab23/internal/web/run.go#L176
https://github.com/thomiceli/opengist/blob/864880b4421efe93930ef986780ba9679507ab23/internal/web/run.go#L189

Maybe we could change the URL of the admin panel to allow a user named admin..?

**Comment by poblabs** [comment]
Ah, that makes sense. I'm happy to use another username, just happened to try admin first and saw it was giving me an error 😄 If you want to leave it as-is, I'm fine with that. Feel free to close this issue if so!
