### ISSUE TITLE
Problems with GItea OAuth

### ISSUE THREAD

**Issue by Shuenhoy** [thomiceli/opengist#24]
Great work! However, I meet some problems with my private Gitea instance:

* If the first account is logged in with Gitea, It will not be treated as admin account
* Disable-signup also prevents a new Gitea user login (My Gitea instance disabled signup already, so all users from Gitea are verified.)

Suggestions:
Add a new option like `gitea_limited`, when it's true, all users should be from Gitea, which means sign-up would be disabled and login widget should also not appear, only the "continue with Gitea" button is shown (similar to Drone).

Thanks!

**Comment by thomiceli** [comment]
Thanks for the feedback, i will fix the first item.
For the second item, i would rather have an option in the admin panel to disable logins/signups with login and password.

Thoughts ?

**Comment by Shuenhoy** [comment]
> Thanks for the feedback, i will fix the first item. For the second item, i would rather have an option in the admin panel to disable logins/signups with login and password.
> 
> Thoughts ?

Thanks for your reply!
I think it's ok to have the option in the admin panel.

**Comment by josefandersson** [comment]
> i would rather have an option in the admin panel to disable logins/signups with login and password

Hey @thomiceli what's the thought process behind whether an option should go in the admin panel or the config? My initial thought was that no option should go in the Admin panel since it's unnecessary and just arbitrarily spreads settings up into two kinds. Instead I feel that the Admin panel should solely be for user/data administration, that cannot reasonably be done via config file.

**Comment by thomiceli** [comment]
> > i would rather have an option in the admin panel to disable logins/signups with login and password
> 
> Hey @thomiceli what's the thought process behind whether an option should go in the admin panel or the config? My initial thought was that no option should go in the Admin panel since it's unnecessary and just arbitrarily spreads settings up into two kinds. Instead I feel that the Admin panel should solely be for user/data administration, that cannot reasonably be done via config file.

I had the same reasoning, then it turned out it would be painful to have some of the options in the config file (see #5 and #8). So i like to put here boolean configuration which doesn't need a server restart (also like Gitea does it, see attached)

<img width="479" alt="Screenshot 2023-05-06 at 04 03 18" src="https://user-images.githubusercontent.com/27960254/236592901-5c439177-aad5-4b41-8559-995660e86773.png">


..although I admit I should rework the UI of this part of the admin panel to make it a bit better

**Comment by josefandersson** [comment]
I understand where you're coming from but I'm not convinced by the mentioned issues. Registration could always be allowed when when no user exist in db no matter the settings and I don't think having to restart the server for major setting changes is unreasonable, especially on a small scale service like this one.

That said, I am not against settings in the admin panel over a config file. If options in the admin panel is the way forward then I would just make sure to be strict about options in config solely being prerequisites for service startup (which you've already done a good job of). OAuth options could be moved away perhaps? external-url? http.git-enabled? (Not sure if the libs you have used handle these being changed on the fly.)

Sorry for off-topic!

**Comment by saaremaa** [comment]
I set up the integration as described in the instructions (https://github.com/thomiceli/opengist#configure-oauth) . Connected Gitea and Opengist. When i try to log in through the user Gitea, an error occurs. Error 400 Bad Request Cannot complete user auth.  What could be wrong?
