### ISSUE TITLE
Allow pushing of directories

### ISSUE THREAD

**Issue by KopiNinja** [thomiceli/opengist#364]
I encountered the following error message when trying to push a directory:
```shell
>git push -u origin master
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 16 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (7/7), 1.29 MiB | 13.94 MiB/s, done.
Total 7 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
remote:
remote: Pushing files in directories is not allowed:
remote:   dist/assets/index-C6IM6O8l.css (7a07b8d)
remote:   dist/assets/index-CLX_rAEX.js (7a07b8d)
remote:   dist/index.html (7a07b8d)
remote:
To http://127.0.0.1:6157/init
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'http://127.0.0.1:6157/init'
```
It would be great if you could enable pushing of directories. ☺️

**Comment by thomiceli** [comment]
I think you should rather use Gitea if you want to store a repository with directories

https://github.com/go-gitea/gitea

**Comment by KopiNinja** [comment]
Ok 😔, thanks anyway! This is the best Gist alternative I've found!
Sometimes I need to send directories to Gist, and if I could send them to OpenGist too, I would completely switch from Gist.

**Comment by brainchild0** [comment]
Gitea serves a different function from Opengist. 

Gitea hosts repositories that are publicly discoverable, with access regulated by site-managed credentials.

Opengist hosts repositories that may remain undiscovered by the public, based on the address being obfuscated, while otherwise accessible without restriction.

Many actual use cases arise for cloning an arbitrary repository such that it be accessible without credentials, but remain effectively private due to the address being unpublished and obfuscated. 

May I ask, why is pushing directories prohibited? 

The constraint seems to me as an example of "crippled by design".
